# Generated by Django 5.2.4 on 2025-08-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título de la notificación",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido de la notificación", verbose_name="Mensaje"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INFO", "Información"),
                            ("AVISO", "Aviso"),
                            ("URGENTE", "Urgente"),
                            ("EVENTO", "Evento"),
                            ("SISTEMA", "Sistema"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "para_todos",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, se enviará a todos los usuarios",
                        verbose_name="Para todos los usuarios",
                    ),
                ),
                (
                    "incluir_admins",
                    models.BooleanField(
                        default=True, verbose_name="Incluir administradores"
                    ),
                ),
                (
                    "incluir_managers",
                    models.BooleanField(default=True, verbose_name="Incluir managers"),
                ),
                (
                    "incluir_usuarios",
                    models.BooleanField(
                        default=True, verbose_name="Incluir usuarios regulares"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha hasta la cual la notificación será visible",
                        null=True,
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si la notificación está activa y visible",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "url_accion",
                    models.URLField(
                        blank=True,
                        help_text="URL a la que redirigir cuando se haga clic en la notificación",
                        null=True,
                        verbose_name="URL de acción",
                    ),
                ),
                (
                    "texto_boton",
                    models.CharField(
                        blank=True,
                        help_text="Texto del botón de acción",
                        max_length=50,
                        null=True,
                        verbose_name="Texto del botón",
                    ),
                ),
                (
                    "destinatarios_especificos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usuarios específicos que recibirán la notificación",
                        related_name="notificaciones_recibidas_especificas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatarios específicos",
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionLeida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "notificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="notificaciones.notificacion",
                        verbose_name="Notificación",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_leidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación leída",
                "verbose_name_plural": "Notificaciones leídas",
                "unique_together": {("notificacion", "usuario")},
            },
        ),
    ]
