# Generated by Django 5.2.4 on 2025-08-07 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacionleida",
            options={
                "ordering": ["-fecha_lectura"],
                "verbose_name": "Notificación leída",
                "verbose_name_plural": "Notificaciones leídas",
            },
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="destinatarios_especificos",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="incluir_admins",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="incluir_managers",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="incluir_usuarios",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="para_todos",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="remitente",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="texto_boton",
        ),
        migrations.RemoveField(
            model_name="notificacion",
            name="url_accion",
        ),
        migrations.AddField(
            model_name="notificacion",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificaciones_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="nivel_usuario_objetivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Administradores"),
                    ("MANAGER", "Managers"),
                    ("USER", "Usuarios"),
                ],
                help_text="Nivel de usuarios que recibirán la notificación",
                max_length=10,
                null=True,
                verbose_name="Nivel de usuario objetivo",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="usuarios_objetivo",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios específicos que recibirán la notificación",
                related_name="notificaciones_dirigidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="activa",
            field=models.BooleanField(
                default=True,
                help_text="Si está activa, la notificación será visible para los usuarios",
                verbose_name="Activa",
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="fecha_expiracion",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha después de la cual la notificación no será visible",
                null=True,
                verbose_name="Fecha de expiración",
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="prioridad",
            field=models.CharField(
                choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta")],
                default="media",
                max_length=10,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("sistema", "Sistema"),
                    ("evento", "Evento"),
                    ("personal", "Personal"),
                ],
                default="general",
                max_length=20,
                verbose_name="Tipo de notificación",
            ),
        ),
    ]
