# Generated by Django 5.2.4 on 2025-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="evidencias",
            field=models.URLField(
                blank=True,
                help_text="Enlace a carpeta/archivo en la nube (Drive, OneDrive, Dropbox, etc.)",
                verbose_name="Liga de evidencias",
            ),
        ),
    ]
