# Generated by Django 5.2.4 on 2025-08-20 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_evento_evidencias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="fecha_evento",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Día en que se realizará el evento",
                verbose_name="Fecha del evento",
            ),
        ),
    ]
