# Generated by Django 5.2.5 on 2025-08-08 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("agenda", "Eventos en Agenda"),
                            ("semana", "Eventos de la Semana"),
                            ("mes", "Eventos del Mes"),
                            ("carpeta_ejecutiva", "Eventos con Carpeta Ejecutiva"),
                            ("personalizado", "Reporte Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("xlsx", "Excel (XLSX)"), ("pdf", "PDF")],
                        max_length=10,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Reporte"),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "fecha_inicio_filtro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio (Filtro)"
                    ),
                ),
                (
                    "fecha_fin_filtro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Fin (Filtro)"
                    ),
                ),
                (
                    "incluir_detalles",
                    models.BooleanField(default=True, verbose_name="Incluir Detalles"),
                ),
                (
                    "solo_confirmados",
                    models.BooleanField(
                        default=False, verbose_name="Solo Eventos Confirmados"
                    ),
                ),
                (
                    "total_eventos",
                    models.IntegerField(default=0, verbose_name="Total de Eventos"),
                ),
                (
                    "archivo_generado",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta del Archivo"
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "ordering": ["-fecha_generacion"],
            },
        ),
    ]
